### ISSUE TITLE
If one of lemmas is failed and one is successed - the request shouldn't be entirely failed

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-translation-service#12]
**For Example:**

Success - https://ats.alpheios.net/lat/por?input=caelum
Failed - https://ats.alpheios.net/lat/por?input=caelus
Failed - https://ats.alpheios.net/lat/por?input=caelus,caelum

**Comment by balmas** [comment]
this turned out not to be a problem with the code, but with the deployment environment. If it misses a translation it tries to insert it into a log of misses. The database wasn't writeable in the production environment so it was crashing.
